In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from scipy.fft import fft


## load the dataset

In [3]:
df = pd.read_csv("dataset/normalized_data.csv")
df

eeg_1    eeg_2    eeg_3    eeg_4   eeg_5    eeg_6    eeg_7    eeg_8  \
0     0.7177  -0.2062   0.0475   1.0721  2.4135   3.5125   3.7577   2.7633   
1   -20.2720 -15.5270  -7.3470   1.1873  7.7569  11.8050  14.1470  15.7500   
2    -2.5855  -3.6533  -3.1125  -1.5704 -0.2837  -0.3124  -1.8101  -3.9264   
3     3.1062   3.9020   4.1897   4.0014  3.4469   2.5849   1.4279   0.0445   
4     4.8654   4.2604   3.1231   1.7460  0.6860   0.5555   1.7299   4.1115   
..       ...      ...      ...      ...     ...      ...      ...      ...   
568   3.9657   5.3286   5.9334   5.4893  4.1019   2.3230   0.9462   0.6367   
569  -0.7658   0.6194   2.6931   4.2242  4.2618   2.7016   0.3394  -1.6152   
570   7.9655  11.3100  12.2670  10.9120  8.0865   4.9417   2.4252   0.9726   
571  -0.6448   1.3528   1.6686   0.5742 -0.8300  -1.3065  -0.2264   2.0804   
572   0.1489   0.4428   1.1452   2.7253  5.1110   7.6149   9.2060   8.9938   

       eeg_9   eeg_10  ...  eeg_243  eeg_244  eeg_245  eeg_246  eeg_247  \
0     0.7151  -1.5270  ...   9.8659   6.0245  -0.3442  -6.7022 -10.5920   
1    16.7530  16.4740  ... -14.8110 -11.2060  -4.8725   1.8731   6.2072   
2    -5.3829  -5.3230  ...  -0.1838  -3.6101  -8.3515 -12.8430 -15.1760   
3    -1.3564  -2.4403  ...  14.7390  16.0430  16.1770  15.4330  14.1300   
4     7.0969   9.7958  ...   0.2532   0.0332  -1.3112  -3.5680  -5.8331   
..       ...      ...  ...      ...      ...      ...      ...      ...   
568   1.5860   3.3815  ...   0.1096  -2.8541  -5.3169  -6.8093  -7.1329   
569  -2.2325  -1.3196  ...  -2.5776  -1.2234   0.1361   0.8815   0.7860   
570   0.4893   0.5447  ...  -5.3580  -4.1075  -2.6476  -1.2086   0.0964   
571   4.5637   6.1062  ...  -4.0059  -3.2825  -2.2467  -0.9428   0.3840   
572   6.6802   2.7586  ...   1.5601  -0.1996  -1.1388  -0.8973   0.5084   

     eeg_248  eeg_249  eeg_250  score  normalized_form  
0   -10.7050  -7.2834  -1.8025      9         0.905440  
1     6.1948   1.8273  -4.8429      7         0.723446  
2   -14.1210  -9.8510  -3.9632      8         0.809585  
3    12.4790  10.6100   8.6729      8         0.813472  
4    -6.8665  -5.7612  -2.5252      9         0.898316  
..       ...      ...      ...    ...              ...  
568  -6.4084  -5.0492  -3.6339     10         0.986399  
569   0.1151  -0.5665  -0.7658     10         0.988990  
570   1.2556   2.2963   3.1921     10         0.987047  
571   1.3054   1.3794   0.3913      9         0.901554  
572   2.6073   4.6034   5.6604      9         0.898964  

[573 rows x 252 columns]

In [4]:
df.iloc[:, :-2]

eeg_1    eeg_2    eeg_3    eeg_4   eeg_5    eeg_6    eeg_7    eeg_8  \
0     0.7177  -0.2062   0.0475   1.0721  2.4135   3.5125   3.7577   2.7633   
1   -20.2720 -15.5270  -7.3470   1.1873  7.7569  11.8050  14.1470  15.7500   
2    -2.5855  -3.6533  -3.1125  -1.5704 -0.2837  -0.3124  -1.8101  -3.9264   
3     3.1062   3.9020   4.1897   4.0014  3.4469   2.5849   1.4279   0.0445   
4     4.8654   4.2604   3.1231   1.7460  0.6860   0.5555   1.7299   4.1115   
..       ...      ...      ...      ...     ...      ...      ...      ...   
568   3.9657   5.3286   5.9334   5.4893  4.1019   2.3230   0.9462   0.6367   
569  -0.7658   0.6194   2.6931   4.2242  4.2618   2.7016   0.3394  -1.6152   
570   7.9655  11.3100  12.2670  10.9120  8.0865   4.9417   2.4252   0.9726   
571  -0.6448   1.3528   1.6686   0.5742 -0.8300  -1.3065  -0.2264   2.0804   
572   0.1489   0.4428   1.1452   2.7253  5.1110   7.6149   9.2060   8.9938   

       eeg_9   eeg_10  ...  eeg_241  eeg_242  eeg_243  eeg_244  eeg_245  \
0     0.7151  -1.5270  ...   6.4512   9.8178   9.8659   6.0245  -0.3442   
1    16.7530  16.4740  ... -12.3200 -14.8970 -14.8110 -11.2060  -4.8725   
2    -5.3829  -5.3230  ...   1.7532   1.4155  -0.1838  -3.6101  -8.3515   
3    -1.3564  -2.4403  ...   8.8898  12.2290  14.7390  16.0430  16.1770   
4     7.0969   9.7958  ...  -0.9779  -0.2740   0.2532   0.0332  -1.3112   
..       ...      ...  ...      ...      ...      ...      ...      ...   
568   1.5860   3.3815  ...   4.9531   2.9321   0.1096  -2.8541  -5.3169   
569  -2.2325  -1.3196  ...  -2.8046  -3.2384  -2.5776  -1.2234   0.1361   
570   0.4893   0.5447  ...  -5.9760  -6.0857  -5.3580  -4.1075  -2.6476   
571   4.5637   6.1062  ...  -4.6760  -4.4657  -4.0059  -3.2825  -2.2467   
572   6.6802   2.7586  ...   5.5435   3.6243   1.5601  -0.1996  -1.1388   

     eeg_246  eeg_247  eeg_248  eeg_249  eeg_250  
0    -6.7022 -10.5920 -10.7050  -7.2834  -1.8025  
1     1.8731   6.2072   6.1948   1.8273  -4.8429  
2   -12.8430 -15.1760 -14.1210  -9.8510  -3.9632  
3    15.4330  14.1300  12.4790  10.6100   8.6729  
4    -3.5680  -5.8331  -6.8665  -5.7612  -2.5252  
..       ...      ...      ...      ...      ...  
568  -6.8093  -7.1329  -6.4084  -5.0492  -3.6339  
569   0.8815   0.7860   0.1151  -0.5665  -0.7658  
570  -1.2086   0.0964   1.2556   2.2963   3.1921  
571  -0.9428   0.3840   1.3054   1.3794   0.3913  
572  -0.8973   0.5084   2.6073   4.6034   5.6604  

[573 rows x 250 columns]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=["score","normalized_form"]), df["normalized_form"], test_size=0.2, random_state=42)

## base random forest

In [6]:
# Train a Random Forest Regressor
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

# Predict on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test,y_pred)
mape

0.23998704851828226

In [16]:
y_pred.max()

0.9558225388601036

In [13]:
y_test.describe()

count    115.000000
mean       0.892065
std        0.144839
min        0.085492
25%        0.897992
50%        0.905440
75%        0.988018
max        0.998705
Name: normalized_form, dtype: float64

In [17]:
y_train.describe()

count    458.000000
mean       0.902048
std        0.101020
min        0.000000
25%        0.895887
50%        0.904145
75%        0.987694
max        1.000000
Name: normalized_form, dtype: float64

mape

In [12]:
for actual, pred in zip(y_test, y_pred):
    print("Actual:", actual, "\tPredicted:", pred)

Actual: 0.9980569948186528 	Predicted: 0.8874676165803104
Actual: 0.8147668393782384 	Predicted: 0.9405634715025906
Actual: 0.905440414507772 	Predicted: 0.8447797927461138
Actual: 0.8147668393782384 	Predicted: 0.9344883419689115
Actual: 0.897020725388601 	Predicted: 0.9220854922279789
Actual: 0.905440414507772 	Predicted: 0.9193976683937821
Actual: 0.8957253886010363 	Predicted: 0.8734002590673575
Actual: 0.9060880829015544 	Predicted: 0.844093264248705
Actual: 0.905440414507772 	Predicted: 0.8458354922279793
Actual: 0.9060880829015544 	Predicted: 0.9220272020725392
Actual: 0.9028497409326424 	Predicted: 0.9017551813471499
Actual: 0.9034974093264247 	Predicted: 0.9176295336787561
Actual: 0.9941709844559584 	Predicted: 0.9075712435233156
Actual: 0.9974093264248703 	Predicted: 0.9075388601036266
Actual: 0.9093264248704664 	Predicted: 0.8992940414507771
Actual: 0.9922279792746114 	Predicted: 0.8993393782383413
Actual: 0.9034974093264247 	Predicted: 0.9361528497409324
Actual: 0.994818652

The results are not satisfactory on Random forest regressor

## freq bands base implementation

In [7]:
# Function to convert time-domain signals to frequency-domain signals
def time_to_frequency_domain(signal):
    fft_result = fft(signal)
    # Assuming signal is sampled at 250 Hz, calculate the frequency bins
    freqs = np.fft.fftfreq(len(signal), 1/250)
    return freqs, np.abs(fft_result)

In [8]:
# Define frequency bands
frequency_bands = [(4, 8), (8, 12), (12, 20), (20, 30)]

! 12-20Hz Frequency band gets MSE: 0.019546689609481756, it is the most meaningful frequency band according to experiments.\
12-20 Hz Band ---> Alpha Rhytm 


# TODOS: 
* mape hesaplama
* rf - svr - lstm 
* farklı frekans aralıkları  
* bar chart

In [12]:
for band in frequency_bands:
    # Extract EEG signals corresponding to the frequency band
    eeg_band = df.loc[:, 'eeg_1':'eeg_250']
    # Convert to frequency domain
    freqs, freq_domain_signals = time_to_frequency_domain(eeg_band)
    # Find indices corresponding to the frequency band
    band_indices = np.where((freqs >= band[0]) & (freqs <= band[1]))[0]
    # Take the mean amplitude across the frequency band for each sample
    freq_domain_signals_band = freq_domain_signals[:, band_indices].mean(axis=1)
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(freq_domain_signals_band, df['normalized_form'], test_size=0.2, random_state=42)
    
    # Train a Random Forest Regressor
    rf_model = RandomForestRegressor(random_state=42)
    rf_model.fit(X_train.reshape(-1, 1), y_train)
    
    # Predict on the test set
    y_pred = rf_model.predict(X_test.reshape(-1, 1))
    # Evaluate the model
    mse = mean_squared_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    print(f"Frequency band: {band}, MSE: {mse}")
    print(f"Frequency band: {band}, MAPE: {mape}")
    
    # diff_count = 0
    
    # for actual, pred in zip(y_test, y_pred):
    #     diff = abs(actual - pred)
    #     if diff < 0.1:
    #         print("Actual:", actual, "\tPredicted:", pred, "\tDiff:",diff)
    #         diff_count = diff_count + 1
    # print("count of difference: ",diff_count)
    # diff_count = 0
    


[10 11 12 13 14 15 16 17 18]
573
Frequency band: (4, 8), MSE: 0.023801261805102465
Frequency band: (4, 8), MAPE: 0.2564334868624624
[19 20 21 22 23 24 25 26 27]
573
Frequency band: (8, 12), MSE: 0.023890843569115344
Frequency band: (8, 12), MAPE: 0.2570967829033705
[28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
573
Frequency band: (12, 20), MSE: 0.019546689609481756
Frequency band: (12, 20), MAPE: 0.24370953112371005
[46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68]
573
Frequency band: (20, 30), MSE: 0.02659585203994389
Frequency band: (20, 30), MAPE: 0.27149489639612046


I also show the difference between actual and predicted values where diff > 0.2 means roughly more than 2 scores